### ISSUE TITLE
How to start

### ISSUE THREAD

**Issue by Remor61** [gregsdennis/Manatee.Trello#130]
I must do a winform that can interact with Trello (add boards and this kind of things), but I have no ideia of what to do after installing the NuGet packages. I know C# and I made some projects with visual Studio, but I really haven't found anything that teaches me how to  start with Manatee.Trello from the zero. I hope you can help me.

**Comment by gregsdennis** [comment]
Thanks for the question. I'd be happy to help.

To start, have you read through the wiki pages (specifically the Usage page)?

**Comment by Remor61** [comment]
Thanks!

Yes, I had, but I never did anything with API's and I'm really lost

**Comment by Remor61** [comment]
Now I was able to get the name of the boards with the url from [API Introduction](https://developers.trello.com/v1.0/docs/api-introduction#section--a-name-auth-your-first-api-call-a-):
https://api.trello.com/1/boards/{idBoard}?key={yourKey}&token={yourToken}

But I would like to use your API, and I'm not getting to do this until this moment.

**Comment by gregsdennis** [comment]
> I would like to have a button in my winform to add an board, for exemple.

Do you mean you want an existing board to appear in your app, or do you mean that you want to create a new board?

### Existing boards

The existing boards that you have access to could be in one of two places.

The first is under the static property `Member.Me`.  This property contains the details about the person who authorized the token (`TrelloAuthorization.UserToken`) and is of type `Member` (well, `Me` actually, but that inherits `Member`).  This type exposes a `Boards` property from which you can get all personal boards for that member.

The second is under a the same property for the `Organization` type.  Trello has renamed organizations to teams in their user documentation, but the object is the same.  To get an organization, you can use the constructor like you have for the board in your *program.cs* file, or you can enumerate the `Organizations` property on a `Member` object.  Once you have an organization, enumerate the `Boards` property just like you would for a member.

### Creating boards

To create a board, you need write permissions for who is to be the owner of the board.  The token you're using will define what permissions the member has allowed.  Usually these are created with full permissions, but you'll want to check the URL you use to create the token.

Organizations can also specify the permissions for a member within it.  If a member has permission to create boards within an organization, then the call will work; otherwise an error will be returned from Trello.

To create a board, get the `Boards` collection from the intended owner (either the member or the organization), and call the `Add()` method, passing in the board name.  A `Board` object will be returned to you.

-----------

This library has been created with OO programming in mind.  The intent is that the client (that's you) works with Trello entities as you would any other object in .Net, and the library manages calling the API in the background.

**Comment by Remor61** [comment]
I want to create a new board. Is there somewhere I can see all the methods?

**Comment by gregsdennis** [comment]
I don't yet have that sort of documentation, except in the XML comments, which are shown as a tooltip in Visual Studio.

I do have #62 open to address that, however.

**Comment by Remor61** [comment]
I have some other doubt. In this line: 

`var board = new Board("[board ID]");`

How can I get the ID if I want to create a new board?

**Comment by Remor61** [comment]
And is there some way to use the API for multiple users? I'd have to ask them to get the key code?

**Comment by Remor61** [comment]
I need to get the lists from a board, how can I do that? I'm only getting to do that in public boards, but I need to do in private ones

**Comment by gregsdennis** [comment]
Please read the wiki.  Specifically the parts on the [Getting Started](https://github.com/gregsdennis/Manatee.Trello/wiki/Getting-started) page under the "More on authorization" section.

**Comment by gregsdennis** [comment]
@Remor61 I have updated the docs to include API details.  Please let me know if this resolves your need.

**Comment by Remor61** [comment]
It does, thanks!
