### ISSUE TITLE
Add more parameters to requests to support nested resources better

### ISSUE THREAD

**Issue by odysseus1973** [gregsdennis/Manatee.Trello#244]
Hello!

Is it possible in any way to download the board and all its contents, with archive cards a small number of requests? If you ask for everything individually, then it's very slow and we get to limit the number of requests. We need to download the contents of the board once a month.

Thanks!

**Comment by gregsdennis** [comment]
I had #233 open for a while.  While the calls listed in that issue are made, only one call is used to download all of the data.  It has extensively customized query parameters that I'm just not set up to generate.

For now, you can play around with the batch call on TrelloProcessor.  You'd have to pass in the board, its `Lists` property, and its `Cards` property.  However, I haven't tested a scenario where an entity and its members are all batched together.

If that doesn't work, I'm open to the idea of a special `board.DeepRefresh()` extension method that adds all of the required parameters since this is likely a common scenario.

**Comment by odysseus1973** [comment]
> For now, you can play around with the batch call on TrelloProcessor. You'd have to pass in the board, its Lists property, and its Cards property. However, I haven't tested a scenario where an entity and its members are all batched together.

Lists and Cards property of board contains 0 items and if I put it in TrelloProcessor.Refresh nothing happens.

**Comment by gregsdennis** [comment]
Ah, yes.  I did a cursory check and saw `IRefreshable`.  Sorry.  Brain fart.  I'll play around with some ideas you might try in the current state.

**Comment by gregsdennis** [comment]
Okay.  It looks like the relational stuff I did in #222 has a small issue.  In trying to ensure the full list was downloaded on a card, I ensure `list` is included in a query parameter, which means that it's not included in the collection of fields to download when a card is included in other requests (like boards and lists).  Because the list isn't downloaded, the relational functionality won't work.  I'll have to fix this.

Once I have that done, you should be able to do something like this:

```csharp
TrelloConfiguration.EnableConsistencyProcessing = true;
Board.DownloadedFields |= Board.Fields.Cards;
var board = _factory.Board(TrelloIds.BoardId);
await board.Refresh(false, ct);
```

That *should* populate all of the downloaded cards into their respective `List.Cards` collections.  I'll be sure to have a test around it as well.

**Comment by gregsdennis** [comment]
I have made some changes on branch **bug/244-relationships-not-full-relational** to incorporate more query parameters into the request so that the above code downloads as much as possible.

I'm going to continue working on this to fill out other requests as the API allows.  You can probably expect an update in a few days.  I'll post back to this issue when I publish it.

**Comment by gregsdennis** [comment]
I'll be pushing v3.3.0 soon to resolve this.
