### ISSUE TITLE
Unable to set Card.DueDate to correct time

### ISSUE THREAD

**Issue by gebradley88** [gregsdennis/Manatee.Trello#37]
I'm having and issue setting the due date on cards, specifically the time of day.

For example, if I assign a due time of 8/10/2016 at 5:45 PM, the due date gets set to the correct date, but the time is 5:45 AM. However, if I use the same date but a few hours later, it works fine. 9:45 PM is an example of a time that works.

I have looked at issue #35 , and I made sure to be on v1.5.1. It seems very odd that some times work, but some times don't.

Let me know if there is something I'm doing wrong.

Thanks!

**Comment by gregsdennis** [comment]
Can you post examples of when it works and when it doesn't, please?

**Comment by gebradley88** [comment]
Sorry about that. I was typing in a hurry and forgot that would probably be helpful.

So the following adds a due date of 5:45 AM to the card, instead of 5:45 PM.
`card.DueDate = Convert.ToDateTime("8/12/2016 5:45:00PM");`

This however adds the correct time of 9:45 PM.
`card.DueDate = Convert.ToDateTime("8/12/2016 9:45:00PM");`

**Comment by gregsdennis** [comment]
What is your time zone?  I need to try to replicate the behaviour.

**Comment by gebradley88** [comment]
EST

**Comment by gregsdennis** [comment]
I found the issue.  When serializing the dates, my format string was slightly off.  I was using a 12-hour format for the hour instead of 24.  This caused anything 1 PM and after in UTC to be posted as 12-hours previous.

For your example, the 5 PM EST translates to 10 PM UTC, but it would be encoded as 10 AM UTC, and when the Trello UI translated this back to EST, it would show 5 AM.  But the 9 PM EST translates to 2 AM UTC the following day because 2 AM is before 1 PM, the UI would translate that back to 9 PM properly.

Will have a new version of Manatee.Trello.ManateeJson posted soon.

**Comment by gregsdennis** [comment]
Please see Manatee.Trello.ManateeJson v1.5.2.
