### ISSUE TITLE
How to create a new board ?

### ISSUE THREAD

**Issue by Moon519** [gregsdennis/Manatee.Trello#39]
Hi,
First i would like to thank you for creating this amazing API. Very easy to use, keep it up!

One thing that I can't get to work is creating a new board. I saw a class named BoardCollection with an "add" method, but I don't know in which context it should be use.

Can you help me ?

Thanks

**Comment by gregsdennis** [comment]
Hello, @moon519!  Thanks for using Manatee.Trello.

The `BoardCollection` can be found as properties on the `Member` and `Organization` objects (and on `Me` by inheritance from `Member`).  On the `Member` object, it's a `ReadOnlyBoardCollection`, though.  Which you use to add a board depends on who you want to own the board.

If you want to add a private board (only visible to you), use the `Member.Me.Boards.Add()` method.

If you want to add a board to an organization (Trello now calls them "teams"), use the `Organization.Boards.Add()` method.

Also remember that you can always change the organization for a board at any time by assigning an `Organization` or `null` to the `Board.Organization` property.

Finally, before you go messing about with organizations, make sure you have the permissions necessary to make those changes.  Otherwise Trello will return an error and an exception will be thrown.

**Comment by Moon519** [comment]
Nice I will try that! Thank you for answering :)

**Comment by indrapranesh** [comment]
Hi,
  I have been trying to use the method `Member.Me.Boards.Add()` but this shows error,
Also when I create an instance for the member and then I pass on the values (memberid and authentication),
I don't find an Add method for it like this `member.Boards.Add()` ,where `member` is the instance of a Member.
Please Help.
Thank You.

**Comment by gregsdennis** [comment]
@indrapranesh what is the error you're getting?

As described above, the `Member` object exposes a read only collection for boards, so there's no `Add()` method.
