### ISSUE TITLE
Board labels only returning a max of 50 labels

### ISSUE THREAD

**Issue by ardentra** [gregsdennis/Manatee.Trello#71]
I posted this question on stack overflow. We are limited to 50 labels getting returned in a board. You mentioned an extension method we could use to overcome that limit? If you can point me in the right direction I'd be happy to help out and submit a PR.

**Comment by gregsdennis** [comment]
I took a look at it last night, and there's some infrastructure for the label collections that's a bit different than the other collections, primarily because I get the labels with the object they belong to (card or board).

For example, when I get cards in a list, it's a dedicated API call which has a `limit` parameter.  But labels come with the rest of the data for cards and boards so I built this collections a little differently.

Because of that, I'm not sure the extension method will work the same.  I need to look at the API docs a bit more to see if I can pass a label limit on a card fetch call.

You're welcome to look at how the collections and their extension method work and the API docs to see if you can work it out.  In the end, I think I may have to split the labels to a dedicated call like the other collections.

**Comment by gregsdennis** [comment]
Ref; [SO question](http://stackoverflow.com/q/42698320/878701)

**Comment by gregsdennis** [comment]
The current implementation of labels on cards has the labels downloaded with the card object.  In order to implement limit/filter on labels, I'd need to do one of the following:

1. Find a request parameter for label limit and incorporate that parameter in the `GET card` call, or
2. Implement labels as a separate collection, like I have for other collections.

Unfortunately, neither of these options work.

1. The `GET card` request URI doesn't support a `labelLimit` parameter.
2. There is no `GET card/labels` call that I can use to support an independent label collection.

This seems to be truly a limitation of the Trello API, and I can't do anything about it.

**Comment by gregsdennis** [comment]
For BOARDS:

I *have* been able to implement both filtering and limits for labels collections on boards.  I will publish soon.

**Comment by gregsdennis** [comment]
Please see branch **feature/limits-for-labels**

**Comment by gregsdennis** [comment]
Please see version 1.17.0 for the new functionality.

**Comment by ardentra** [comment]
you da man! Thanks @gregsdennis !
