### ISSUE TITLE
Card positioning not working

### ISSUE THREAD

**Issue by Caloyski** [gregsdennis/Manatee.Trello#96]
I tried this and doesn't seem to work:

var card = list.Cards.Add(cardName, cardDescription, new Position(index), null, null, null, null);

**Comment by Caloyski** [comment]
The card is added but positioned in the last position.

index is 3 and i have 10 items

**Comment by gregsdennis** [comment]
The value in the Position property is not an index. Rather, Trello determines position using a floating point value. When moving a card, the new position is the average of the position values of the cards above and below the new location in the list.

So to insert a card at index three, the position needs to be set to the average of the positions of the cards currently at indices two and three.

**Comment by gregsdennis** [comment]
@Caloyski does this explanation resolve the issue?

**Comment by ronwarner** [comment]
I briefly discussed this with you, @gregsdennis , on Stack Overflow some time ago.  I'm curious if you know of any documentation Trello provides of this somewhat strange positioning system.  All that I know about it, I've learned by examining your code base!  It begs the question, how did you come to understand it?  I see no real mention of it in the Trello API docs.  I'd like to get a better understanding of it.  I sometimes wonder how this is sustainable on Trello's end.  Do they periodically reset all the position numbers on a given list's cards to reasonable values?  It seems like, otherwise, they'd eventually have some collisions happening.  For instance, what happens if one tries to insert a card between two adjacent cards which differ in position by only the smallest difference that can be represented by the floating point data type?  Similarly, what happens if circumstances lead to the bottom card having the largest possible value as its position?  Can no more cards be added below it?

**Comment by gregsdennis** [comment]
@ronwarner, they have no documentation on it.  It's what I've experimented with and a couple emails with their support team from long ago when this project began.

Honestly, I have no answers to your questions, and I've asked many of them myself.  They may have considered many of these, but I suspect that they're likely considered edge cases.  At any rate, cards in Manatee.Trello regularly update and so would adjust to whatever strategy Trello employs.

If you're concerned about moving cards frequently, you can periodically reset the list by explicitly setting the position for all of the cards in a list.

**Comment by ronwarner** [comment]
@gregsdennis - That's good enough for me, then.  I doubt I'll run into one of those edge cases, I just wasn't sure if there was something I should read more about before doing too much with this.  When I've used Position, it's usually been to sort a list, in which case just giving all the cards new positions based on integers works just fine.
